**Q1. What is a database?   Differentiate between SQL and NoSQL databases.**

---
A database is a structured collection of data that is organized and managed to provide quick access, retrieval, and update. It can be classified into two main types:<br>


<B>SQL</B><br>
<B>NoSQL</B>
</br>
Difference between Sql and Nosql are


*       SQL databases are relational databases that use Structured Query Language (SQL) for defining and manipulating the data. They have a predefined schema, use tables to store data, and ensure ACID (Atomicity, Consistency, Isolation, Durability) properties. Examples include MySQL, PostgreSQL, and Oracle.<br></br>


*     NoSQL databases are non-relational databases that provide a more flexible and scalable way of storing and retrieving data. They do not necessarily require a fixed schema, use different data models (key-value, document, columnar, graph), and often offer better performance for certain types of applications. Examples include MongoDB, Cassandra, and Redis.



---

**Q2. What is DDL? Explain why CREATE, DROP, ALTER, and TRUNCATE are used with an example.**
<br>
       DDL (Data Definition Language) is used to define the structure of a database. <br></br>
**CREATE**: It is used to create objects like tables, indexes, etc.


```
CREATE TABLE Students (
  id INT PRIMARY KEY,
  name VARCHAR(50),
  age INT
);

```


**DROP**: It is used to delete objects like tables, indexes, etc. <br>
`DROP TABLE Students;`




**ALTER**: It is used to modify existing database objects.


```
ALTER TABLE Students
ADD COLUMN grade CHAR(1);

```

**TRUNCATE**: It is used to remove all records from a table.


```
TRUNCATE TABLE Students;


```



---

**Q3. What is DML? Explain INSERT, UPDATE, and DELETE with an example.**


<br>
DML (Data Manipulation Language) is used to manipulate the data itself.
<br>

**INSERT**: It is used to insert new records into a table.


```
INSERT INTO Students (id, name, age)
VALUES (1, 'John', 20);

```



**UPDATE**: It is used to modify existing records in a table.


```
UPDATE Students
SET age = 21
WHERE name = 'John';

```




**DELETE**: It is used to delete records from a table.


```
DELETE FROM Students
WHERE name = 'John';

```
<br>


---

**Q4. What is DQL? Explain SELECT with an example.**
<br>
DQL (Data Query Language) is used to retrieve data from the database.

**SELECT**: It is used to retrieve data from a database.


```
SELECT * FROM Students;
```

**Q5. Explain Primary Key and Foreign Key.**<br>

    Primary Key: It is a column or a set of columns that uniquely

*    Primary Key: It is a column or a set of columns that uniquely identifies each row in a table. It ensures that the data in the column(s) is unique and not null. For example, id column in a table can be a primary key.</br>



* Foreign Key: It is a column or a set of columns in a table that refers to the primary key in another table. It establishes a link between two tables, enforcing referential integrity. For instance, if a table Orders has a column customer_id referencing the id column in a Customers table, customer_id in Orders is a foreign key.

  

---

**Q6. Write a Python code to connect MySQL to Python. Explain the cursor() and execute() method.**




```
import mysql.connector

# Establish connection
mydb = mysql.connector.connect(
    host="localhost",
    user="yourusername",
    password="yourpassword",
    database="yourdatabase"
)

if mydb.is_connected():
    print("Connected to MySQL!")

# Perform operations here (execute queries, etc.)

# Close connection
mydb.close()

```





*       cursor(): The cursor() method creates a cursor object that allows Python to interact with the MySQL database.

*      execute(): The execute() method is used to execute SQL queries passed as arguments to the method.




---

**Q7. Give the order of execution of SQL clauses in an SQL query.**
The order of execution in an SQL query generally follows this sequence:

    SELECT: Determines which columns or data to retrieve.
    FROM: Specifies the table(s) from which to retrieve the data.
    WHERE: Filters the rows based on specified conditions.
    GROUP BY: Groups the rows based on common values in specified columns.
    HAVING: Filters the grouped rows based on specified conditions.
    ORDER BY: Sorts the result set based on specified columns.
    LIMIT / OFFSET: Limits the number of rows returned (optional).